branches:
  only:
    - 'master'

language: php

php:
  - 5.3
  - 5.4

env:
  - BRANCHES=1.5/master
  - BRANCHES=1.4/master

before_install:
  - git clone --recursive --quiet --branch=$BRANCHES git://github.com/fuel/fuel.git "$HOME/fuelphp"

before_script:
  - ln -sf "`pwd`" "$HOME/fuelphp/fuel/packages/ldapauth"
  - cp -fr "`pwd`/tests/travis-ci/*"  "$HOME/fuelphp/fuel/app/config/"
  - mysql -e 'create database fuel_test;'

script:
  - phpunit -c "$HOME/fuelphp/fuel/core/phpunit.xml" --group=LdapAuthPackage --coverage-text

